name: Test docker

on: 
  push:
    paths:
     - 'pyproject.toml'
     - 'poetry.lock'
     - 'Dockerfile'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-actions@v2
        